#include <iostream>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
using namespace std;
{
cout<<"Enter thr even number";
cout<<"total number of even number";


 for(i=1;i<N;i++)
 {
 cout<<"even %d\n"<<i<<endl;
 }
 return 0;
